Repository os2display/display-api-service, pull requests merged in 2025-03, with the labels that each got.

#233 Fixed issues with calendar api feed source modifiers
  CHANGELOG.md
  docs/calender-api-feed.md
  src/Feed/CalendarApiFeedType.php
  tests/Feed/CalendarApiFeedTypeData.php
  tests/Feed/CalendarApiFeedTypeTest.php
Labels: bug

#231 New feed source: Eventdatabasen v2
  .env
  CHANGELOG.md
  config/packages/cache.yaml
  config/services.yaml
  infrastructure/itkdev/display-api-service/etc/confd/templates/env.local.tmpl
  infrastructure/os2display/display-api-service/etc/confd/templates/env.local.tmpl
  src/Feed/EventDatabaseApiFeedType.php
  src/Feed/EventDatabaseApiV2FeedType.php
  src/Feed/EventDatabaseApiV2Helper.php
  src/Feed/OutputModel/Poster/Event.php
  src/Feed/OutputModel/Poster/ImageUrls.php
  src/Feed/OutputModel/Poster/Occurrence.php
  src/Feed/OutputModel/Poster/Organizer.php
  src/Feed/OutputModel/Poster/Place.php
  src/Feed/OutputModel/Poster/Poster.php
  src/Feed/OutputModel/Poster/PosterOption.php
  src/Feed/OutputModel/Poster/PosterOutput.php
Labels: enhancement

#236 Notified Feed Type bug when media url is null
  CHANGELOG.md
  src/Feed/NotifiedFeedType.php
Labels: bug

#235 Eventdatabase v2 feed source fixes
  CHANGELOG.md
  src/Feed/EventDatabaseApiV2FeedType.php
  src/Feed/EventDatabaseApiV2Helper.php
  src/Feed/OutputModel/Poster/Poster.php
Labels: bug

#237 Release 2.3.0
  .env
  CHANGELOG.md
  config/packages/cache.yaml
  config/services.yaml
  docs/calender-api-feed.md
  infrastructure/itkdev/display-api-service/etc/confd/templates/env.local.tmpl
  infrastructure/os2display/display-api-service/etc/confd/templates/env.local.tmpl
  src/Feed/CalendarApiFeedType.php
  src/Feed/EventDatabaseApiFeedType.php
  src/Feed/EventDatabaseApiV2FeedType.php
  src/Feed/EventDatabaseApiV2Helper.php
  src/Feed/NotifiedFeedType.php
  src/Feed/OutputModel/Poster/Event.php
  src/Feed/OutputModel/Poster/ImageUrls.php
  src/Feed/OutputModel/Poster/Occurrence.php
  src/Feed/OutputModel/Poster/Organizer.php
  src/Feed/OutputModel/Poster/Place.php
  src/Feed/OutputModel/Poster/Poster.php
  src/Feed/OutputModel/Poster/PosterOption.php
  src/Feed/OutputModel/Poster/PosterOutput.php
  tests/Feed/CalendarApiFeedTypeData.php
  tests/Feed/CalendarApiFeedTypeTest.php
Labels: release

#232 Updated user emails in README
  CHANGELOG.md
  README.md
Labels: documentation

#238 Screen Status: Added environment variables to infrastructure files
  .env
  CHANGELOG.md
  config/services.yaml
  infrastructure/itkdev/display-api-service/etc/confd/templates/env.local.tmpl
  infrastructure/os2display/display-api-service/etc/confd/templates/env.local.tmpl
Labels: bug
