Repository os2display/display-api-service, pull requests merged in 2025-09, with the labels that each got.

#271 Online check
  .docker/templates/default.conf.template
  CHANGELOG.md
  README.md
  config/routes.yaml
  public/client/online-check/1pixel.png
  public/client/online-check/index.html
Labels: enhancement

#287 Align with 2.5.2. Cleaned up themes and fixtures.
  .github/workflows/playwright.yaml
  .gitignore
  CHANGELOG.md
  README.md
  Taskfile.yml
  assets/shared/slide-utils/global-styles.css
  assets/shared/slide-utils/slide-util.jsx
  assets/shared/templates/calendar.json
  assets/shared/templates/calendar/calendar-single-booking-helper.jsx
  assets/shared/templates/calendar/calendar-single-booking.jsx
  assets/shared/templates/image-text.jsx
  assets/shared/templates/image-text/image-text.scss
  assets/shared/templates/news-feed.jsx
  assets/shared/templates/news-feed/news-feed.scss
  assets/template/fixtures/slide-fixtures.js
  assets/template/index.jsx
  config/packages/api_platform.yaml
  docs/release-example.json
  docs/themes/example.css
  docs/themes/themes.md
  docs/v2-changelogs/admin.md
  docs/v2-changelogs/api.md
  docs/v2-changelogs/template.md
  fixtures/public/fixtures/example.css
  fixtures/public/fixtures/template/images/author.jpg
  fixtures/public/fixtures/template/images/logo.png
  fixtures/public/fixtures/template/images/mountain1.jpeg
  fixtures/public/fixtures/template/images/mountain2.jpeg
  fixtures/public/fixtures/template/images/mountain3.jpeg
  fixtures/public/fixtures/template/images/mountain4.jpeg
  fixtures/public/fixtures/template/images/sunset-full-hd.jpg
  fixtures/public/fixtures/template/images/vertical.jpg
  fixtures/public/fixtures/template/videos/test.mp4
  fixtures/public/fixtures/template/videos/video.mp4
  migrations/Version20250828084617.php
  public/fixtures/template/images/dokk1-rss-template-bg.jpg
  public/fixtures/template/images/dokk1-shapes-animated.svg
  public/themes/aakb.css
  public/themes/aarhus.css
  public/themes/bautavej.css
  public/themes/blixen.css
  public/themes/dokk1.css
  public/themes/infostander.css
  public/themes/mso.css
  src/Controller/Api/InteractiveController.php
  src/Entity/Tenant/InteractiveSlideConfig.php
  src/Exceptions/ForbiddenException.php
  src/Exceptions/NotAcceptableException.php
  src/Exceptions/TooManyRequestsException.php
  src/InteractiveSlide/InstantBook.php
  src/InteractiveSlide/InteractiveSlideInterface.php
  src/Repository/InteractiveSlideRepository.php
  src/Service/InteractiveSlideService.php
  tests/Service/InteractiveServiceTest.php
Labels: enhancement

#290 4905 clean up grid generation a bit
  assets/admin/components/screen/util/grid-generation-and-select.jsx
  assets/admin/components/screen/util/grid.jsx
Labels: enhancement

#289 5317: instagram template tests and changed slide fixtures
  assets/template/fixtures/slide-fixtures.js
  assets/tests/template/template-instagram.spec.js
Labels: enhancement

#291 5452: missing a trnaslation
  assets/admin/components/util/multi-and-table/select-slides-table.jsx
  assets/admin/translations/da/common.json
Labels: enhancement

#292 5452: fix missing translation
  assets/admin/components/playlist/shared-playlists-column.jsx
  assets/admin/translations/da/common.json
Labels: enhancement

#299 5317 fix failing campaign test
  assets/tests/admin/admin-campaign.spec.js
Labels: bug

#288 Added command to migrate config.json files to .env variables
  CHANGELOG.md
  README.md
  UPGRADE.md
  composer.json
  src/Command/UpdateCommand.php
  src/Command/Utils/ConvertConfigJsonToEnvCommand.php
  src/Command/Utils/GenerateUlid.php
Labels: enhancement

#306 iframe template test
  assets/template/fixtures/slide-fixtures.js
  assets/tests/template/template-iframe.spec.js
Labels: enhancement

#293 Rewrite get data to fix bug
  CHANGELOG.md
  assets/admin/components/playlist-drag-and-drop/playlist-drag-and-drop.jsx
  assets/admin/components/playlist/campaign-form.jsx
  assets/admin/components/screen/screen-form.jsx
  assets/admin/components/screen/util/grid-generation-and-select.jsx
  assets/admin/components/util/drag-and-drop-table/drag-and-drop-table.jsx
  assets/admin/components/util/fetch-data-hook.js
  assets/admin/components/util/forms/multiselect-dropdown/pagination-button.jsx
  assets/admin/components/util/helpers/map-to-ids.js
  assets/admin/components/util/multi-and-table/select-groups-table.jsx
  assets/admin/components/util/multi-and-table/select-playlists-table.jsx
  assets/admin/components/util/multi-and-table/select-screens-table.jsx
  assets/admin/components/util/multi-and-table/select-slides-table.jsx
  assets/admin/components/util/table/table.jsx
  assets/admin/translations/da/common.json
  assets/tests/admin/admin-campaign.spec.js
Labels: bug

#286 Release 2.5.2
  CHANGELOG.md
  config/packages/api_platform.yaml
  migrations/Version20250828084617.php
  src/Controller/InteractiveController.php
  src/Entity/Tenant/InteractiveSlideConfig.php
  src/Exceptions/ForbiddenException.php
  src/Exceptions/NotAcceptableException.php
  src/Exceptions/TooManyRequestsException.php
  src/InteractiveSlide/InstantBook.php
  src/InteractiveSlide/InteractiveSlideInterface.php
  src/Repository/InteractiveSlideRepository.php
  src/Service/InteractiveSlideService.php
  tests/Service/InteractiveServiceTest.php
Labels: release
